(()=>{
'use strict';
const WA='254780079982';
const KEY='simba-ordering-v5';
let cart=[];
try{cart=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(cart))cart=[];}catch(e){cart=[];}
const money=n=>'KSh '+Number(n||0).toLocaleString('en-KE');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const cards=()=>[...document.querySelectorAll('#products .reference-product-card')].filter(c=>c.querySelector('h3'));
const product=card=>{const name=(card.querySelector('h3')?.textContent||'Product').trim();const price=Number((card.querySelector('.reference-product-footer strong')?.textContent||'').replace(/[^0-9]/g,''))||0;const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return{id,name,price};};
const count=()=>cart.reduce((s,x)=>s+x.qty,0);
const total=()=>cart.reduce((s,x)=>s+x.price*x.qty,0);
const save=()=>{localStorage.setItem(KEY,JSON.stringify(cart));render();decorate();};
const add=p=>{const x=cart.find(v=>v.id===p.id);if(x)x.qty++;else cart.push({...p,qty:1});save();pulse();};
const change=(id,d)=>{const x=cart.find(v=>v.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(v=>v.id!==id);save();};
function ensure(){if(document.getElementById('o5-fab'))return;document.body.insertAdjacentHTML('beforeend',`<button id="o5-fab" type="button" aria-label="Open cart"><span>🛒</span><b id="o5-count">0</b></button><div id="o5-cart" aria-hidden="true"><aside id="o5-panel"><header><div><small>YOUR ORDER</small><h2>Shopping Cart</h2></div><button id="o5-close" type="button" aria-label="Close">×</button></header><div id="o5-items"></div><div class="o5-summary"><div><span>Total</span><strong id="o5-total">KSh 0</strong></div><button id="o5-proceed" type="button">PROCEED TO CHECKOUT</button></div></aside></div><div id="o5-checkout" aria-hidden="true"><div class="o5-checkout-box"><div class="o5-checkout-head"><div><small>CHECKOUT</small><h2>Customer details</h2></div><button id="o5-checkout-close" type="button" aria-label="Close">×</button></div><p class="o5-sub">Enter your details and we’ll prepare the complete quotation for WhatsApp.</p><label>NAME<input id="o5-name" autocomplete="name" placeholder="Your full name"></label><label>PHONE NUMBER<input id="o5-phone" autocomplete="tel" inputmode="tel" placeholder="07xx xxx xxx"></label><label>LOCATION<input id="o5-location" autocomplete="address-level2" placeholder="Town / area"></label><div class="o5-checkout-actions"><button id="o5-back" class="o5-back" type="button">BACK TO CART</button><button id="o5-whatsapp" class="o5-whatsapp" type="button">CONTINUE TO WHATSAPP</button></div></div></div>`);document.getElementById('o5-fab').onclick=openCart;document.getElementById('o5-close').onclick=closeCart;document.getElementById('o5-proceed').onclick=openCheckout;document.getElementById('o5-checkout-close').onclick=closeCheckout;document.getElementById('o5-back').onclick=()=>{closeCheckout();openCart();};document.getElementById('o5-whatsapp').onclick=sendWhatsApp;document.getElementById('o5-cart').addEventListener('click',e=>{if(e.target.id==='o5-cart')closeCart();});document.getElementById('o5-checkout').addEventListener('click',e=>{if(e.target.id==='o5-checkout')closeCheckout();});}
function render(){ensure();document.getElementById('o5-count').textContent=count();document.getElementById('o5-total').textContent=money(total());const box=document.getElementById('o5-items');box.innerHTML=cart.length?cart.map(x=>`<div class="o5-row"><div><strong>${esc(x.name)}</strong><small>${money(x.price)} each</small></div><div class="o5-qty"><button type="button" data-o5="minus" data-id="${esc(x.id)}">−</button><span>${x.qty}</span><button type="button" data-o5="plus" data-id="${esc(x.id)}">+</button></div></div>`).join(''):'<div class="o5-empty">Your cart is empty.<br><small>Add products using ADD TO CART.</small></div>';box.querySelectorAll('[data-o5]').forEach(b=>b.onclick=()=>change(b.dataset.id,b.dataset.o5==='plus'?1:-1));document.getElementById('o5-proceed').disabled=!cart.length;}
function makeButton(p){const b=document.createElement('button');b.type='button';b.className='o5-add';b.textContent='ADD TO CART';b.onclick=()=>add(p);return b;}
function decorate(){cards().forEach(card=>{const old=card.querySelector('.reference-add');if(old)old.style.display='none';if(!card.querySelector('.o5-add')){const f=card.querySelector('.reference-product-footer')||card;f.appendChild(makeButton(product(card)));}});document.querySelectorAll('#products .reference-steel-list > div').forEach(row=>{const old=row.querySelector('button');if(old)old.style.display='none';if(row.querySelector('.o5-steel-add'))return;const name=(row.querySelector('strong')?.textContent||'Steel').trim();const price=Number((row.querySelector('span')?.textContent||'').replace(/[^0-9]/g,''))||0;const b=makeButton({id:name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name:'REINFORCEMENT STEEL '+name.toUpperCase(),price});b.classList.add('o5-steel-add');b.textContent='ADD';row.appendChild(b);});}
function openCart(){ensure();render();document.getElementById('o5-cart').classList.add('open');document.getElementById('o5-cart').setAttribute('aria-hidden','false');}
function closeCart(){const x=document.getElementById('o5-cart');if(x){x.classList.remove('open');x.setAttribute('aria-hidden','true');}}
function openCheckout(){if(!cart.length){alert('Please add at least one product to your cart.');return;}ensure();closeCart();document.getElementById('o5-checkout').classList.add('open');document.getElementById('o5-checkout').setAttribute('aria-hidden','false');}
function closeCheckout(){const x=document.getElementById('o5-checkout');if(x){x.classList.remove('open');x.setAttribute('aria-hidden','true');}}
function sendWhatsApp(){if(!cart.length){alert('Please add at least one product to your cart.');return;}const n=document.getElementById('o5-name').value.trim(),p=document.getElementById('o5-phone').value.trim(),l=document.getElementById('o5-location').value.trim();if(!n||!p||!l){alert('Please enter your name, phone number and location.');return;}const lines=cart.map(x=>`- ${x.name} x${x.qty} = ${money(x.price*x.qty)}`).join('\n');const text=`Hello Simba Cement Kenya, I would like a quotation.\n\nName: ${n}\nPhone: ${p}\nLocation: ${l}\n\nItems:\n${lines}\n\nEstimated total: ${money(total())}`;window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(text),'_blank','noopener');}
function pulse(){const b=document.getElementById('o5-fab');if(!b)return;b.classList.remove('pulse');void b.offsetWidth;b.classList.add('pulse');}
function boot(){ensure();render();decorate();setTimeout(decorate,500);setTimeout(decorate,1500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();